language: julia

julia:
  - 1.1

jobs:
  include:

    - stage: "Documentation"
      julia: 1.1

      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


    - stage: "Testing"
      julia: 1.1

      stript:
        - julia test/runtest.jl
      after_success: skip
