language: julia

julia:
  - 1.1

jobs:
  include:

    - stage: "Testing"

      julia: 1.1

      stript:
        - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.test(coverage=true)'

      after_success:
        - julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'


    - stage: "Documentation"

      julia: 1.1

      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl

      after_success: skip
