language: julia

julia:
  - 1.1

jobs:
  include:

    - stage: "Testing"

      julia: 1.1

      s—Åript:
        - julia -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'

      after_success: skip


    - stage: "Documentation"

      julia: 1.1

      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl

      after_success: skip
